Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/11/2020
Var
// Seção de Declarações das variáveis 
OCUPADO :LOGICO

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
ESCREVA("ELE ESTA OCUPADO : ")
LEIA(OCUPADO)
ESCREVA(OCUPADO)
Fimalgoritmo